version: '3'
services:
  school-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: school-backend:1.0.0
    container_name: school-backend
    restart: unless-stopped
    ports:
      - '5445:5445'
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://admin:password@postgres-db:5432/school?schema=public"
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
