-- AlterTable
ALTER TABLE "Assessments" ALTER COLUMN "assignment" SET DEFAULT 0,
ALTER COLUMN "assesment" SET DEFAULT 0,
ALTER COLUMN "examination" SET DEFAULT 0,
ALTER COLUMN "overall" SET DEFAULT 0,
ALTER COLUMN "grade" DROP NOT NULL;

-- AlterTable
ALTER TABLE "BranchAccess" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Result" ALTER COLUMN "grade" DROP NOT NULL,
ALTER COLUMN "remark" DROP NOT NULL;
