on:
  push:
name: 🚀 Deploy on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Install pnpm packages
        run: |
          pnpm install
      - name: Build application
        run: |
          pnpm run build